// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Creates a new user and returns the created user
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes a user by ID
	DeleteUser(ctx context.Context, userID uuid.UUID) error
	// Checks if an email is already registered
	EmailExists(ctx context.Context, email string) (bool, error)
	// Retrieves a single user by their email
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Retrieves a single user by their ID
	GetUserByID(ctx context.Context, userID uuid.UUID) (User, error)
	// Retrieves all users with optional filtering
	ListUsers(ctx context.Context) ([]User, error)
	// Retrieves users filtered by status
	ListUsersByStatus(ctx context.Context, status string) ([]User, error)
	// Updates a user's information
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Checks if a user exists by ID
	UserExists(ctx context.Context, userID uuid.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
