// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
/*
name: <MethodName> :<command>

:one: Expects exactly one row (returns a struct and an error).
:many: Expects zero or more rows (returns a slice).
:exec: Executes a query without returning rows (returns only an error).
:execrows: Returns the number of affected rows.

*/

INSERT INTO users (
    first_name,
    last_name,
    email,
    phone,
    age,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING user_id, first_name, last_name, email, phone, age, status, created_at, updated_at
`

type CreateUserParams struct {
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     string      `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Age       pgtype.Int4 `json:"age"`
	Status    string      `json:"status"`
}

// Creates a new user and returns the created user
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

// Deletes a user by ID
func (q *Queries) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE email = $1
)
`

// Checks if an email is already registered
func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, first_name, last_name, email, phone, age, status, created_at, updated_at FROM users
WHERE email = $1
`

// Retrieves a single user by their email
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, first_name, last_name, email, phone, age, status, created_at, updated_at FROM users
WHERE user_id = $1
`

// Retrieves a single user by their ID
func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, first_name, last_name, email, phone, age, status, created_at, updated_at FROM users
ORDER BY created_at DESC
`

// Retrieves all users with optional filtering
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Age,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStatus = `-- name: ListUsersByStatus :many
SELECT user_id, first_name, last_name, email, phone, age, status, created_at, updated_at FROM users
WHERE status = $1
ORDER BY created_at DESC
`

// Retrieves users filtered by status
func (q *Queries) ListUsersByStatus(ctx context.Context, status string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Age,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    email = COALESCE($4, email),
    phone = COALESCE($5, phone),
    age = COALESCE($6, age),
    status = COALESCE($7, status),
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
RETURNING user_id, first_name, last_name, email, phone, age, status, created_at, updated_at
`

type UpdateUserParams struct {
	UserID    uuid.UUID      `json:"user_id"`
	FirstName pgtype.Text    `json:"first_name"`
	LastName  pgtype.Text    `json:"last_name"`
	Email     pgtype.Text    `json:"email"`
	Phone     pgtype.Text    `json:"phone"`
	Age       pgtype.Int4    `json:"age"`
	Status    NullUserStatus `json:"status"`
}

// Updates a user's information
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE user_id = $1
)
`

// Checks if a user exists by ID
func (q *Queries) UserExists(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
